[[docs]]
  name = "Overview"
  weight = 10
  identifier = "overview"
  url = "/docs/overview/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"


[[main]]
  name = "Documentation"
  identifier = "docs"
  url = "/docs/overview/introduction/"
  weight = 10

[[main]]
  name = "âš¡ Quick Start"
  weight = 12
  url = "/docs/overview/quick-start"
  parent = "docs"

[[main]]
  name = "ğŸ“„ Overview"
  weight = 13
  url = "/docs/overview"
  parent = "docs"

[[main]]
  name = "ğŸ” How to guides"
  weight = 14
  url = "/docs/how-to"
  parent = "docs"

[[main]]
  name = "ğŸ­ Engines"
  weight = 15
  url = "/docs/engines"
  parent = "docs"

[[main]]
  name = "ğŸ§© Integrations"
  weight = 16
  identifier = "integrations"
  url = "/docs/integrations"
  parent = "docs"

[[main]]
  name = "Dashboard ->"
  weight = 97
  url = "/dashboard"
  parent = "docs"

[[main]]
  name = "Swagger ->"
  weight = 97
  url = "/swagger"
  parent = "docs"
  target = "_blank"

[[main]]
  name = "Postman ->"
  weight = 98
  url = "https://www.postman.com/devlikeapro/workspace/waha/collection/35390377-42210829-5a92-45c5-a001-6a453c5d764a?action=share&creator=35390377"
  parent = "docs"

[[main]]
  name = "OpenAPI JSON ->"
  weight = 99
  url = "https://waha.devlike.pro/swagger/openapi.json"
  parent = "docs"

[[main]]
  name = "WAHA Plus"
  weight = 20
  identifier = "waha-plus"

[[main]]
  name = "â• WAHA Plus"
  weight = 10
  url = "/docs/how-to/plus-version"
  parent = "waha-plus"

[[main]]
  name = "Patron Portal ->"
  weight = 20
  url = "https://portal.devlike.pro/"
  parent = "waha-plus"

[[main]]
  name = "Get on Patreon ->"
  weight = 60
  url = "https://patreon.com/wa_http_api"
  parent = "waha-plus"

[[main]]
  name = "Get on Boosty ->"
  weight = 50
  url = "https://boosty.to/wa-http-api"
  parent = "waha-plus"
[[main]]
  name = "Get with Crypto ->"
  weight = 70
  url = "/pricing/#how-to-donate"
  parent = "waha-plus"

[[main]]
  name = "Blog"
  weight = 60
  url = "/blog"

[[main]]
  name = "Pricing"
  weight = 70
  url = "/pricing"

[[main]]
  name = "Contact"
  weight = 80
  url = "/contact"

[[main]]
  name = "ğŸŒ Language"
  identifier = "language"
  weight = 99

[[main]]
  name = "More"
  identifier = "more"
  weight = 90

[[main]]
  name = "WhatsApp Automation with n8n"
  parent = "more"
  url = "/whatsapp-n8n/"

[[main]]
  name = "WhatsApp Channels Automation"
  parent = "more"
  url = "/whatsapp-channels/"

[[main]]
  name = "WhatsApp Status Automation"
  parent = "more"
  url = "/whatsapp-status/"

[[main]]
  name = "ğŸ‡¦ğŸ‡ª Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© (Arabic)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=ar&hl=ar&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡§ğŸ‡© à¦¬à¦¾à¦‚à¦²à¦¾ (Bengali)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=bn&hl=bn&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡¬ğŸ‡§ English (English)"
  parent="language"
  url="https://waha.devlike.pro/"

[[main]]
  name = "ğŸ‡®ğŸ‡· ÙØ§Ø±Ø³ÛŒ (Persian)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=fa&hl=fa&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡®ğŸ‡³ à¤¹à¤¿à¤‚à¤¦à¥€ (Hindi)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=hi&hl=hi&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡®ğŸ‡© Bahasa Indonesia (Indonesian)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=id&hl=id&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡§ğŸ‡·ğŸ‡µğŸ‡¹ PortuguÃªs (Portuguese)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=pt&hl=pt&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡·ğŸ‡º Ğ ÑƒÑÑĞºĞ¸Ğ¹ (Russian)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=ru&hl=ru&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡ªğŸ‡¸ EspaÃ±ol (Spanish)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=es&hl=es&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡¹ğŸ‡· TÃ¼rkÃ§e (Turkish)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=tr&hl=tr&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡ºğŸ‡¦ Ğ£ĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ° (Ukrainian)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=uk&hl=uk&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡µğŸ‡° à¨ªà©°à¨œà¨¾à¨¬à©€ (Punjabi)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=pa&hl=pa&u=https://waha.devlike.pro/&client=webapp"

[[main]]
  name = "ğŸ‡«ğŸ‡· FranÃ§ais (French)"
  parent="language"
  url="https://translate.google.com/translate?sl=en&tl=fr&hl=fr&u=https://waha.devlike.pro/&client=webapp"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/devlikeapro/waha"
  post = "v0.1.0"
  weight = 10

#[[social]]
#  name = "Twitter"
#  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#  url = "https://twitter.com/getdoks"
#  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
